#!/bin/sh
################################################################################
#      This file is part of LibreELEC - https://LibreELEC.tv
#      Copyright (C) 2016 Team LibreELEC
#
#  LibreELEC is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 2 of the License, or
#  (at your option) any later version.
#
#  LibreELEC is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with LibreELEC.  If not, see <http://www.gnu.org/licenses/>.
################################################################################

# remove old ljalves files
echo "removing old sources ..."
rm -rf ljalves
rm -rf ljalves-*

################################################################################

# media_build dl
echo "getting media_build sources ..."
  if [ ! -d media_build.git ]; then
    #git clone --depth=1 https://github.com/ljalves/media_build.git ljalves/media_build
    git clone --depth=1 git://linuxtv.org/media_build.git ljalves/media_build
  fi

echo "cleaning media_build sources ..."
  rm -rf ljalves/media_build/.git

################################################################################

# ljalves tbs drivers dl
echo "getting ljalves sources ... !!! huge !!!"
  if [ ! -d linux_media.git ]; then
    git clone --depth=1 https://github.com/ljalves/linux_media.git -b latest ljalves/media
  fi

  cd ljalves/media
    git pull
    GIT_REV=`git log -n1 --pretty=format:"%ad" --date=short`

# remove unnessecary files
  rm -rf Documentation
  cd ../..

echo "copying ljalves sources ..."
  rm -rf ljalves-$GIT_REV
  cp -R ljalves ljalves-$GIT_REV

echo "cleaning ljalves sources ..."
  rm -rf ljalves-$GIT_REV/media/.git

################################################################################

echo "packing sources ..."
tar cvJf ljalves-$GIT_REV.tar.xz ljalves-$GIT_REV

echo "remove temporary sourcedir ..."
  rm -rf ljalves-$GIT_REV
  rm -rf ljalves
